name: Sync To Gitee
on:
  push:
  # schedule:
  #  - cron: '0 1 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:dlwxin/mock-server-koa2.git'
          destination-repo: 'git@gitee.com:dlwxin/mock-server-koa2.git'
